server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:10086/eureka
spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///leyou?useUnicode=yes&characterEncoding=utf8
    username: root
    password: root
  rabbitmq:
    host: 127.0.0.1
    username: rose
    password: rose
    virtual-host: /leyou124
    template:
      retry:  #重试策略
        enabled: true  #如果发送失败，重新发送策略开启
        initial-interval: 10000ms    #第一次重试间隔时间
        max-interval: 80000ms    #最后一次重试间隔时间
        multiplier: 2   #每次重试间隔时间的倍数
    publisher-confirms: true    #开启消息的ACK回执确认，如果消费者方抛出一次，则认为没有消息确认
mybatis:
  type-aliases-package: com.winnie.item.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mapper/*.xml
logging:
  level:
    com.winnie: debug
mapper:
  wrap-keyword: "`{0}`"