server:
  port: 8086
spring:
  application:
    name: winnie-sms
  rabbitmq:
    host: 127.0.0.1
    virtual-host: /leyou124
    username: rose
    password: rose
wn:
  sms:
    accessKeyId: www
    accessSecret: www
    regionId: cn-hangzhou
    signName: 乐友商城
    templateCode: SMS_183791543
    sysDomain: dysmsapi.aliyuncs.com
    sysVersion: 2017-05-25
    sysAction: SendSms
