server:
  port: 8085
spring:
  application:
    name: user-service
  rabbitmq:
    host: 127.0.0.1
    virtual-host: /leyou124
    username: rose
    password: rose
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///leyou?useUnicode=yes&characterEncoding=utf8
    password: root
    username: root
  redis:
    host: 127.0.0.1
mybatis:
  type-aliases-package: com.winnie.user.entity
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
logging:
  level:
    com.winnie: debug
wn:
  encoder:
    crypt:
      secret: ${random.uuid} # 随机的密钥，使用uuid
      strength: 10 # 加密强度4~31，决定了密码和盐加密时的运算次数，超过10以后加密耗时会显著增加
  jwt:
    pubKeyPath: D:\\it\\RSAAuth\\rsa_key.pub # 公钥地址
    user:
      cookieName: WN_TOKEN # cookie名称
    app:
      id: 1
      secret: ${spring.application.name}
      headerName: privilege_token