server:
  port: 8084
spring:
  application:
    name: page-service
  thymeleaf:
    cache: false
  rabbitmq:
    host: 127.0.0.1
    virtual-host: /leyou124
    username: rose
    password: rose
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
wn:
  static:
    itemDir: D:\it\leyou\nginx\nginx-1.16.0\html\item
    itemTemplate: item
logging:
  level:
    com.winnie: debug